#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sheep_Wolf.Droid.Resource", IsApplication=true)]

namespace Sheep_Wolf.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int sheep = 2130771968;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int addSheepButton = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int globalLayout = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int listOfSheeps = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int sheeps_container = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int textNameOfSheep = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int textView1 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int textView3 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int textView4 = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int textViewNumbSheep = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int textViewSheep = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int textViewSheepsName = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int view1 = 2130837515;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int SheepCheckList = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int SheepIDLayout = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int Icon = 2130968576;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
