#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sheep_Wolf.Droid.Resource", IsApplication=true)]

namespace Sheep_Wolf.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7F010000
			public const int type_animal = 2130771968;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int sheep = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int wolf = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int addSheepButton = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int animalChoice = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int animalType = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int fotoSheep = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int globalLayout = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int imageAnimal = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int listOfSheeps = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int sheepFoto = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int sheeps_container = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int textNameOfSheep = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int textView1 = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int textView3 = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int textViewNumbSheep = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int textViewSheepAdapter = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int textViewSheepsName = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int textViewSheepsNameAdapter = 2130903055;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int SheepCheckList = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int SheepIDLayout = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int Icon = 2131034112;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
